### ISSUE TITLE
TNC Hangs on Transmit

### ISSUE THREAD

**Issue by W3AXL** [PA7FRN/kissTnc#2]
Hi

I've been working on getting this code running on a custom TNC board. It's almost identical to the MicroModem design, except for using the M328P's internal 8MHz oscillator and a 5V reference as opposed to a 3.3V reference.

Initially I compiled and ran the code without any changes. It would attempt to transmit packets, but get stuck as soon as PTT was enabled and a reset was required. I also tried loopback mode, which had the same result.

I then added debug prints to see where things are getting hung up. Here's a test TX with the data as "TEST" (byte seqeunce `C0 00 54 45 53 54 C0`) :

```
HdlcTnc::setLoopbackTest(1)
HdlcTnc:addByteToTxBuf(84)
HdlcTnc:addByteToTxBuf(69)
HdlcTnc:addByteToTxBuf(83)
HdlcTnc:addByteToTxBuf(84)
HdlcTnc::addFrameEndToTxBuf()                                                      
HdlcTnc::setPtt(1)                                                          
HdlcAfskTx::start()
```

After it sets PTT and starts TX, nothing happens. With additional log prints, I can see that the TNC is just looping `HdlcTnc::getReady()`. It doesn't appear that any of the functions for preparing and sending the AFSK data ever get called. The behavior is the same regardless of whether or not Loopback mode is enabled.

Help would be appreciated!

**Comment by PA7FRN** [comment]
Hi Patrick,

I can not reproduce this issue. Maybe the buffer sizes, RX_BUFFER_SIZE and TX_BUFFER_SIZE are to big.
Also check if the ISR in AfskSampler.cpp is called.

**Comment by PA7FRN** [comment]
Not reproducable
